### PR TITLE
Add "status" option for feeds

### PR DESCRIPTION
**Pull request by pvledoux**
This gives the option to immediately publish or not the imported entries. This allows for instance the editors to make content curation.
This is configurable per feeds.

### CODE REVIEW

**Comment by engram-design** [comment]
Thanks for submitting this! I'm currently working on being able to set defaults for all fields (both core Craft fields and custom fields), so this will likely cover this situation as well. But this might certainly come in handy for the short-term.

One quick question I have - what if the user is mapping a feed node to the Status field for the entry? From what I can tell, this setting would override that? I imagine thats just a matter of moving [Line 175](https://github.com/Tcheu/FeedMe/blob/master/feedme/services/FeedMeService.php#L175) to before the field mapping.

**Comment by pvledoux** [comment]
Great news! Indeed this can be a temporarily solution (I need it for a site in the coming days).

And yes it is a 'override them all' solution ;) but I was not sure where I could set it earlier in the code as I needed that the model exists.

Maybe we can test if $feed->fieldMapping->status exists?

**Comment by pvledoux** [comment]
Hi, sorry I totally had this out of my radar, but my client will need this feature soon. So I merged your latest version. What do you think?

**Comment by pvledoux** [comment]
Hi, I just merged with 1.4.8. Let me know if this pull request needs improvements.

**Comment by pvledoux** [comment]
Hi, not sure what to do with this ;) Do you plan to implement it in a futur version? I just need to know so I can keep I'm fork updated.

**Comment by engram-design** [comment]
Hey there, sorry for not responding. I've been working on this (and much more) in the [2.0.0](https://github.com/engram-design/FeedMe/tree/2.0.0) branch. As an example, have a look at the below way of setting the default status when importing.

screen shot 2016-04-27 at 7 31 41 pm

**Comment by pvledoux** [comment]
Cool! Ok I close it than. Thanks!

**Pull request closed without merging**
