### PR TITLE
#797 making empty strings able to overwrite previous values

### PR DESCRIPTION
**Pull request by floatingbits**
### Description
Treating empty string as legal value that can overwrite current values and will not be ignored in further processing.

### Related issues

#797

### CODE REVIEW

**Comment by boudewijn-zicht** [comment]
@floatingbits Could you please take a look at this?  It seems like a solution for several of our clients as well...

**Comment by floatingbits** [comment]
@boudewijn-zicht I think you wanted to mention @angrybrad. He's the reviewer. I'm just a random developer who suggested a fix ;)

**Comment by boudewijn-zicht** [comment]
Very good point :smile:

Let me try that again...

@angrybrad Could you please take a look at this? It seems like a solution for several of our clients as well...

**Comment by angrybrad** [comment]
@boudewijn-zicht yup, have a tab open to look at this, but it'll probably be next week.

**Comment by boudewijn-zicht** [comment]
> @boudewijn-zicht yup, have a tab open to look at this, but it'll probably be next week.

Awesome, that makes me very happy!

**Comment by mdoorschodt** [comment]
hi angrybrad, could you give us an update please? ik would be so nice if this could be resolved... i've got several clients with feeds that we can't process properly due to this issue

**Comment by tricki** [comment]
This might have been fixed in 5.1.0: 

> Added the “Set Empty Values” feed setting, which determines whether empty values in the feed should be respected or ignored. (https://github.com/craftcms/feed-me/pull/1228, https://github.com/craftcms/feed-me/issues/797, https://github.com/craftcms/feed-me/issues/723, https://github.com/craftcms/feed-me/issues/854, https://github.com/craftcms/feed-me/issues/680)

Source: https://github.com/craftcms/feed-me/blob/develop/CHANGELOG.md#510---2023-03-17

**Comment by i-just** [comment]
The “Set Empty Values” feed setting was added in 5.1.0.

**Pull request closed without merging**
